# Generated by Django 6.0.7 on 2026-07-24 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HesapProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uyelik_tipi', models.CharField(choices=[('bireysel', 'Bireysel Usta Üyeliği'), ('isletme', 'İşletme Üyeliği (Ortak Şifre / Çoklu Erişim)')], default='bireysel', max_length=20, verbose_name='Üyelik Paketi')),
                ('firma_adi', models.CharField(max_length=255, verbose_name='Firma veya Usta Adı')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('varsayilan_seri', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiyatTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renk', models.CharField(choices=[('beyaz', 'Beyaz'), ('antrasit', 'Antrasit'), ('altin_mese', 'Altın Meşe')], default='beyaz', max_length=20)),
                ('kasa', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('ortakayit', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('pencereKanadi', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('kapiKanadi', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('surmeKasa', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('surmeKanadi', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('aluKasa', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('aluOrtakayit', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('aluPencereKanadi', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('aluKapiKanadi', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('aluSurmeKasa', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('aluSurmeKanadi', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('cam', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('camIci', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upvcLambiri', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('aluLambiri', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('tekAcilim', models.DecimalField(decimal_places=2, default=350, max_digits=10)),
                ('ciftAcilim', models.DecimalField(decimal_places=2, default=600, max_digits=10)),
                ('vasistas', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('kapiAksesuar', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('surmeAksesuar', models.DecimalField(decimal_places=2, default=850, max_digits=10)),
                ('sineklik', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('plisePerdeM2', models.DecimalField(decimal_places=2, default=600, max_digits=10)),
                ('surguluSineklikM2', models.DecimalField(decimal_places=2, default=750, max_digits=10)),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyatlar', to='accounts.hesapprofili')),
            ],
            options={
                'unique_together': {('hesap', 'renk')},
            },
        ),
    ]
