# Generated by Django 6.0.7 on 2026-07-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_abonelikpaketi_alter_fiyattablosu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesapprofili',
            name='aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Aktif Müşteri mi?'),
        ),
    ]
