# Generated by Django 6.0.7 on 2026-07-25 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hesapprofili_aktif_mi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(default='İsimsiz Proje', max_length=255, verbose_name='Proje / Müşteri Adı')),
                ('cizim_verisi', models.JSONField(verbose_name='Çizim Datası (JSON)')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeler', to='accounts.hesapprofili', verbose_name='Çizimi Yapan Usta')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': '4 - Projeler',
            },
        ),
    ]
