# Generated by Django 6.0.7 on 2026-07-22 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(max_length=200, verbose_name='Proje / Müşteri Adı')),
                ('musteri_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Müşteri Telefonu')),
                ('teklif_tarihi', models.CharField(max_length=50, verbose_name='Teklif Tarihi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogramaKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalem_adi', models.CharField(max_length=150, verbose_name='Oda / Kalem Adı')),
                ('urun_tipi', models.CharField(max_length=50, verbose_name='Ürün Tipi')),
                ('genislik', models.IntegerField(verbose_name='Genişlik (mm)')),
                ('yukseklik', models.IntegerField(verbose_name='Yükseklik (mm)')),
                ('sag_yukseklik', models.IntegerField(default=1600, verbose_name='Sağ Boy (Açılı için)')),
                ('bolme_sayisi', models.IntegerField(default=1, verbose_name='Bölme Sayısı')),
                ('kanatlar', models.JSONField(default=list, verbose_name='Kanat Tipleri')),
                ('bolme_olculeri', models.JSONField(default=list, verbose_name='Asimetrik Ölçüler')),
                ('renk', models.CharField(max_length=50, verbose_name='Profil Rengi')),
                ('cam_tipi', models.CharField(max_length=50, verbose_name='Cam Tipi')),
                ('sineklik_iste', models.BooleanField(default=False, verbose_name='Sineklik Var mı')),
                ('alt_panel_lambiri', models.BooleanField(default=True, verbose_name='Alt Lambiri Var mı')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kalem Fiyatı (TL)')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepet_kalemleri', to='api.proje')),
            ],
        ),
    ]
