# Generated by Django 6.0.7 on 2026-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renk', models.CharField(choices=[('beyaz', 'Beyaz'), ('antrasit', 'Antrasit Gri'), ('altin_mese', 'Altın Meşe')], default='beyaz', max_length=20)),
                ('upvc_kasa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upvc_ortakayit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upvc_pencere_kanadi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upvc_kapi_kanadi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upvc_surme_kasa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upvc_surme_kanadi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('al_kasa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('al_ortakayit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('al_pencere_kanadi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('al_kapi_kanadi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('al_surme_kasa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('al_surme_kanadi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aksesuar_tek_acilim', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aksesuar_cift_acilim', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aksesuar_vasistas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aksesuar_kapi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aksesuar_surme', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cam_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cam_ici_detay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upvc_lambiri', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aluminyum_lambiri', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('para_birimi', models.CharField(default='TL', max_length=10)),
                ('ondalik_basamak', models.IntegerField(default=0)),
            ],
        ),
    ]
