# Generated by Django 6.0.7 on 2026-07-24 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonelikPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_adi', models.CharField(max_length=100, verbose_name='Paket Adı (Örn: Bireysel, İşletme)')),
                ('aylik_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aylık Ücret (TL)')),
                ('ozellikler', models.TextField(blank=True, null=True, verbose_name='Paket Özellikleri')),
            ],
            options={
                'verbose_name': 'Abonelik Paketi',
                'verbose_name_plural': '1 - Abonelik Paketleri',
            },
        ),
        migrations.AlterModelOptions(
            name='fiyattablosu',
            options={'verbose_name': 'Fiyat Tablosu', 'verbose_name_plural': '3 - Ustaların Fiyat Tabloları'},
        ),
        migrations.AlterModelOptions(
            name='hesapprofili',
            options={'verbose_name': 'Hesap Profili', 'verbose_name_plural': '2 - Hesap Profilleri'},
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='aluKapiKanadi',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='aluLambiri',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='aluPencereKanadi',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='aluSurmeKanadi',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='aluSurmeKasa',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='camIci',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='kapiAksesuar',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='sineklik',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='surmeAksesuar',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='upvcLambiri',
        ),
        migrations.RemoveField(
            model_name='fiyattablosu',
            name='vasistas',
        ),
        migrations.RemoveField(
            model_name='hesapprofili',
            name='uyelik_tipi',
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='aluKasa',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10, verbose_name='Alüminyum Kasa (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='aluOrtakayit',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10, verbose_name='Alüminyum Orta Kayıt (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='cam',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10, verbose_name='Cam (m2)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='ciftAcilim',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10, verbose_name='Çift Açılım (Adet)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='hesap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyatlar', to='accounts.hesapprofili', verbose_name='Ait Olduğu Hesap'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='kapiKanadi',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='UPVC Kapı Kanadı (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='kasa',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='UPVC Kasa (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='ortakayit',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='UPVC Orta Kayıt (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='pencereKanadi',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='UPVC Pencere Kanadı (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='plisePerdeM2',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10, verbose_name='Plise Perde (m2)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='renk',
            field=models.CharField(choices=[('beyaz', 'Beyaz'), ('antrasit', 'Antrasit'), ('altin_mese', 'Altın Meşe')], default='beyaz', max_length=20, verbose_name='Profil Rengi'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='surguluSineklikM2',
            field=models.DecimalField(decimal_places=2, default=750, max_digits=10, verbose_name='Sürgülü Sineklik (m2)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='surmeKanadi',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='UPVC Sürme Kanat (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='surmeKasa',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='UPVC Sürme Kasa (mt)'),
        ),
        migrations.AlterField(
            model_name='fiyattablosu',
            name='tekAcilim',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10, verbose_name='Tek Açılım (Adet)'),
        ),
        migrations.AlterField(
            model_name='hesapprofili',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Giriş Bilgisi'),
        ),
        migrations.AlterField(
            model_name='hesapprofili',
            name='varsayilan_seri',
            field=models.IntegerField(default=70, verbose_name='Varsayılan PVC Serisi'),
        ),
        migrations.AddField(
            model_name='hesapprofili',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.abonelikpaketi', verbose_name='Seçilen Abonelik Paketi'),
        ),
    ]
